In [28]:
import pandas as pd 

df = pd.read_csv("Transactions.csv")


pd.set_option('display.max_columns', None)

pd.set_option('display.max_rows', None)

In [29]:
print(len(df[df.duplicated()]))

# As can be seen there are no duplicates exists

0

In [30]:
# We are going to drop all the column that end with '_ar' since english version of it already exists on the table

column_to_drop = [col for col in df.columns if col.endswith('_ar') ]

column_to_drop

df = df.drop(columns=column_to_drop)

df.head()

,transaction_id,procedure_id,trans_group_id,trans_group_en,procedure_name_en,instance_date,property_type_id,property_type_en,property_sub_type_id,property_sub_type_en,property_usage_en,reg_type_id,reg_type_en,area_id,area_name_en,building_name_en,project_number,project_name_en,master_project_en,nearest_landmark_en,nearest_metro_en,nearest_mall_en,rooms_en,has_parking,procedure_area,actual_worth,meter_sale_price,rent_value,meter_rent_price,no_of_parties_role_1,no_of_parties_role_2,no_of_parties_role_3
0,1-11-2004-2099,11,1,Sales,Sell,04-10-2004,4,Villa,NaN,NaN,Commercial,1,Existing Properties,249,Al Muteena,NaN,NaN,NaN,NaN,Dubai International Airport,Salah Al Din Metro Station,Dubai Mall,NaN,0,860.28,4500000.0,5230.86,NaN,NaN,3.0,1.0,0.0
1,1-11-2011-6898,11,1,Sales,Sell,21-04-2011,3,Unit,60.0,Flat,Residential,1,Existing Properties,390,Burj Khalifa,Burj Khalifa,1462.0,BURJ KHALIFA TOWERS,Burj Khalifa,Burj Khalifa,Buj Khalifa Dubai Mall Metro Station,Dubai Mall,1 B/R,1,89.93,2008888.0,22338.35,NaN,NaN,1.0,1.0,0.0
2,1-11-2008-203212,11,1,Sales,Sell,11-06-2008,3,Unit,60.0,Flat,Residential,1,Existing Properties,343,Al Warsan First,N-09,NaN,NaN,International City Phase 1,NaN,Rashidiya Metro Station,City Centre Mirdif,1 B/R,0,67.00,330000.0,4925.37,NaN,NaN,1.0,1.0,0.0
3,1-11-2010-15769,11,1,Sales,Sell,25-10-2010,3,Unit,60.0,Flat,Residential,1,Existing Properties,350,Al Thanyah Fifth,GREEN LAKES S1,NaN,NaN,Jumeirah Lakes Towers,Burj Al Arab,Damac Properties,Marina Mall,1 B/R,1,100.80,928756.0,9213.85,NaN,NaN,1.0,1.0,0.0
4,1-110-2010-557,110,1,Sales,Lease to Own Registration,24-03-2010,3,Unit,60.0,Flat,Residential,1,Existing Properties,343,Al Warsan First,X-23,NaN,NaN,International City Phase 1,Dubai International Airport,Rashidiya Metro Station,City Centre Mirdif,Studio,0,43.00,290000.0,6744.19,NaN,NaN,4.0,2.0,2.0

In [31]:
# Checking the datatypes

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1151769 entries, 0 to 1151768
Data columns (total 32 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   transaction_id        1151769 non-null  str
 1   procedure_id          1151769 non-null  int64
 2   trans_group_id        1151769 non-null  int64
 3   trans_group_en        1151769 non-null  str
 4   procedure_name_en     1151769 non-null  str
 5   instance_date         1151769 non-null  str
 6   property_type_id      1151769 non-null  int64
 7   property_type_en      1151769 non-null  str
 8   property_sub_type_id  888704 non-null   float64
 9   property_sub_type_en  888704 non-null   str
 10  property_usage_en     1151769 non-null  str
 11  reg_type_id           1151769 non-null  int64
 12  reg_type_en           1151769 non-null  str
 13  area_id               1151769 non-null  int64
 14  area_name_en          1151769 non-null  str
 15  building_name_en      789458 non-null   str
 16  project_number        758451 non-null   float64
 17  project_name_en       758451 non-null   str
 18  master_project_en     944714 non-null   str
 19  nearest_landmark_en   998552 non-null   str
 20  nearest_metro_en      876773 non-null   str
 21  nearest_mall_en       871955 non-null   str
 22  rooms_en              872625 non-null   str
 23  has_parking           1151769 non-null  int64
 24  procedure_area        1151769 non-null  float64
 25  actual_worth          1151769 non-null  float64
 26  meter_sale_price      1151769 non-null  float64
 27  rent_value            34262 non-null    float64
 28  meter_rent_price      34262 non-null    float64
 29  no_of_parties_role_1  1150843 non-null  float64
 30  no_of_parties_role_2  1150843 non-null  float64
 31  no_of_parties_role_3  1150843 non-null  float64
dtypes: float64(10), int64(6), str(16)
memory usage: 281.2 MB

In [32]:
# Now as can be seen, that  instance_date is on string type
# we need to convert to datetime so we are able to work on specific dates

df['date'] = pd.to_datetime(df['instance_date'], format='%d-%m-%Y', errors='coerce')

In [39]:
len(df[df['date'].isnull()])

0

In [40]:
df.isnull().sum()

transaction_id                0
procedure_id                  0
trans_group_id                0
trans_group_en                0
procedure_name_en             0
instance_date                 0
property_type_id              0
property_type_en              0
property_sub_type_id     263065
property_sub_type_en     263065
property_usage_en             0
reg_type_id                   0
reg_type_en                   0
area_id                       0
area_name_en                  0
building_name_en         362311
project_number           393318
project_name_en          393318
master_project_en        207055
nearest_landmark_en      153217
nearest_metro_en         274996
nearest_mall_en          279814
rooms_en                 279144
has_parking                   0
procedure_area                0
actual_worth                  0
meter_sale_price              0
rent_value              1117507
meter_rent_price        1117507
no_of_parties_role_1        926
no_of_parties_role_2        926
no_of_parties_role_3        926
date                          0
dtype: int64

In [ ]:
# As can been seen there are 3 types of transactions: ['Sales', 'Mortgages', 'Gifts']

df['trans_group_en'].unique()

<StringArray>
['Sales', 'Mortgages', 'Gifts']
Length: 3, dtype: str

In [ ]:

# Here i am selecting year by 2023 and transactions by Sales and Mortgages, not including Gifts. 

result = df[(df['date'] >='2023-01-01')
            &
            (df['date'] <='2023-12-31')]

result = result[df['trans_group_en'] != 'Gifts']

result

In [135]:
result.head(5)

,transaction_id,procedure_id,trans_group_id,trans_group_en,procedure_name_en,instance_date,property_type_id,property_type_en,property_sub_type_id,property_sub_type_en,property_usage_en,reg_type_id,reg_type_en,area_id,area_name_en,building_name_en,project_number,project_name_en,master_project_en,nearest_landmark_en,nearest_metro_en,nearest_mall_en,rooms_en,has_parking,procedure_area,actual_worth,meter_sale_price,rent_value,meter_rent_price,no_of_parties_role_1,no_of_parties_role_2,no_of_parties_role_3,date
22,1-102-2023-4596,102,1,Sales,Sell - Pre registration,30-01-2023,3,Unit,60.0,Flat,Residential,0,Off-Plan Properties,350,Al Thanyah Fifth,Seven City JLT,2065.0,SEVEN CITY JLT,Jumeirah Islands,Burj Al Arab,Damac Properties,Marina Mall,Studio,1,35.67,557417.0,15627.05,NaN,NaN,1.0,1.0,0.0,2023-01-30
33,1-102-2023-14616,102,1,Sales,Sell - Pre registration,27-03-2023,4,Villa,4.0,Villa,Residential,0,Off-Plan Properties,485,Me'Aisem First,NaN,2506.0,Jouri Hills,Jumeirah Golf Estates,NaN,NaN,NaN,4 B/R,0,349.71,5266800.0,15060.48,NaN,NaN,1.0,1.0,0.0,2023-03-27
34,1-11-2023-30212,11,1,Sales,Sell,21-09-2023,3,Unit,60.0,Flat,Residential,1,Existing Properties,451,Al Hebiah Fifth,AL RAMTH 11,1924.0,Remraam - Al Ramth,Remraam,Motor City,NaN,NaN,1 B/R,1,53.87,531000.0,9857.06,NaN,NaN,1.0,1.0,0.0,2023-09-21
35,1-102-2023-56228,102,1,Sales,Sell - Pre registration,24-10-2023,3,Unit,60.0,Flat,Residential,0,Off-Plan Properties,482,Hadaeq Sheikh Mohammed Bin Rashid,Lime Gardens,2418.0,Lime Gardens,DUBAI HILLS - PARK,Motor City,First Abu Dhabi Bank Metro Station,Mall of the Emirates,1 B/R,1,60.29,1300000.0,21562.45,NaN,NaN,1.0,1.0,0.0,2023-10-24
71,1-41-2023-18937,41,1,Sales,Delayed Sell,27-09-2023,1,Land,NaN,NaN,Commercial,1,Existing Properties,445,Jabal Ali First,NaN,2262.0,Murooj Al Furjan 2,Al Furjan,NaN,NaN,NaN,NaN,0,612.75,5500000.0,8975.93,NaN,NaN,1.0,1.0,0.0,2023-09-27

In [ ]:
# Here i am saving it to csv to transfer to SQL later

result.to_csv(r'C:\Users\HP\Desktop\Project 1 Upwork\Dubai Project\output.csv', index= False)